spring:
  # 生产环境数据源
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:visit_management}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
    username: ${DB_USERNAME:visit_user}
    password: ${DB_PASSWORD}

    # 生产环境连接池配置
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000

  # JPA生产配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 50
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

  # Redis生产配置
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 3000ms
    database: ${REDIS_DATABASE:0}
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 5

  # 邮件生产配置
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true

# 生产环境日志配置
logging:
  level:
    root: WARN
    com.visitmanagement: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: WARN
  file:
    name: /app/logs/visit-management.log
    max-size: 100MB
    max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 生产环境应用配置
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}

  file:
    upload-path: ${FILE_UPLOAD_PATH:/app/uploads}
    export-path: ${FILE_EXPORT_PATH:/app/exports}
    max-size: ${FILE_MAX_SIZE:10485760}

  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://yourdomain.com}

# 生产环境监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
  security:
    enabled: true

# 生产环境API文档配置
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false