spring:
  # 开发环境数据源
  datasource:
    url: jdbc:mysql://localhost:3306/visit_management?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

  # JPA开发配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Redis开发配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 0

  # 邮件开发配置
  mail:
    host: smtp.qq.com
    port: 587
    username:
    password:
    test-connection: false

# 开发环境日志配置
logging:
  level:
    root: INFO
    com.visitmanagement: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 开发环境应用配置
app:
  file:
    upload-path: ./uploads
    export-path: ./exports

  # 开发环境JWT配置
  jwt:
    secret: dev-secret-key-not-for-production
    expiration: 86400000

  security:
    cors:
      allowed-origins: http://localhost:3000,http://localhost:8080,http://127.0.0.1:3000