server:
  port: 10086

spring:
  profiles:
    active: dev  # 默认启用 dev 环境

  datasource:
    url: jdbc:mysql://127.0.0.1:12100/visit_management?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: bunny
    password: bunny
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 自动建表或更新结构，可根据需要设为 validate / none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 兼容 Spring Boot 2.x 的路径匹配方式

logging:
  level:
    root: INFO

app:
  jwt:
    secret: proshine-jwt-2025
    expiration-in-ms: 86400000       # 用于 @Value("${app.jwt.expiration-in-ms}")
    expiration: 86400000             # 用于 @Value("${app.jwt.expiration}")
    issuer: visit-management-api

file:
  upload-path: ./uploads
  export-path: ./exports